services:
  # 后端 Java 服务
  personal_web_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal_web_backend
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    networks:
      - core-network  # 接入公共网络

  # 前端 Nginx 服务
  personal_web_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: personal_web_frontend
    restart: always
    ports:
      - "8081:80"     # 占用宿主机 8081 端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - personal_web_backend
    networks:
      - core-network

# 核心：声明使用之前创建好的外部网络
networks:
  core-network:
    external: true