-- schema.sql: Initialize MySQL schema
CREATE TABLE IF NOT EXISTS `chat_turn` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `session_id` VARCHAR(128) NOT NULL,
  `user_question` TEXT NOT NULL,
  `assistant_answer` TEXT NOT NULL,
  `sources_json` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `cover_image` VARCHAR(1000),
  `frameworks` VARCHAR(255),
  `online_url` VARCHAR(1000),
  `github_url` VARCHAR(1000),
  `summary` VARCHAR(500),
  `content` LONGTEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `article` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `summary` VARCHAR(1000),
  `content` LONGTEXT,
  `tags` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `daily_stats` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `record_date` DATE NOT NULL UNIQUE,
  `tokens` INT NOT NULL DEFAULT 0,
  `visits` INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rate_limit_whitelist` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `ip` VARCHAR(64) NOT NULL UNIQUE,
  `remark` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `system_log` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `level` VARCHAR(16) NOT NULL DEFAULT 'INFO',
  `module` VARCHAR(64) NOT NULL,
  `message` TEXT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
